#!/bin/bash
# Generate Database Init Script with Vault Passwords
#
# This script retrieves passwords from Vault and generates a SQL script
# that creates users with properly hashed passwords.
#
# Usage: ./generate-db-init.sh
#
# Prerequisites: 
# - Vault must be running and unsealed
# - Vault must contain secrets at secret/app/flask

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT_CONTAINER="vault_server"
VAULT_KEYS_FILE="$SCRIPT_DIR/vault-keys.json"
OUTPUT_FILE="$SCRIPT_DIR/../../be_flask/db_init/001_create_users.sql"

# Helper function to run vault commands in container
vault_exec() {
    docker exec -e VAULT_TOKEN="$VAULT_TOKEN" "$VAULT_CONTAINER" vault "$@"
}

# Helper function to hash password using Python in the backend container
hash_password() {
    local password="$1"
    python3 <<EOF
from werkzeug.security import generate_password_hash
print(generate_password_hash('$password'), end='')
EOF
}

echo "==================================="
echo "Generate Database Init Script"
echo "==================================="
echo ""

# Check if Vault container is running
if ! docker ps --format '{{.Names}}' | grep -q "^${VAULT_CONTAINER}$"; then
    echo "❌ Error: Vault container is not running"
    echo "Please start Vault: docker compose -f docker-compose.vault.yaml up -d"
    exit 1
fi

# Check if vault-keys.json exists
if [ ! -f "$VAULT_KEYS_FILE" ]; then
    echo "❌ Error: vault-keys.json not found"
    echo "Please run init-vault.sh first to initialize Vault."
    exit 1
fi

# Get root token
ROOT_TOKEN=$(jq -r '.root_token' "$VAULT_KEYS_FILE")
VAULT_TOKEN="$ROOT_TOKEN"

echo "Retrieving passwords from Vault..."

# Get passwords from Vault
ADMIN_PASSWORD=$(vault_exec kv get -field=admin_password secret/app/flask)
ALICE_PASSWORD=$(vault_exec kv get -field=alice_password secret/app/flask)
MOD_PASSWORD=$(vault_exec kv get -field=moderator_password secret/app/flask)

echo "✅ Retrieved passwords from Vault"
echo ""
echo "Generating password hashes..."

# Install werkzeug in a temporary container and hash passwords
ADMIN_HASH=$(hash_password "$ADMIN_PASSWORD")
ALICE_HASH=$(hash_password "$ALICE_PASSWORD")
MOD_HASH=$(hash_password "$MOD_PASSWORD")

echo "✅ Generated password hashes"
echo ""
echo "Creating SQL init script..."

# Generate SQL file
cat > "$OUTPUT_FILE" <<EOF
-- Create users table and seed initial users (admin, alice, moderator)
-- This script is executed by the official Postgres image when the DB directory is empty.
--
-- IMPORTANT: This file is auto-generated by vault/scripts/generate-db-init.sh
-- Passwords are retrieved from Vault and hashed using werkzeug.security
--
-- To regenerate with updated passwords:
--   cd vault/scripts && ./generate-db-init.sh

CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY,
    role VARCHAR(32) NOT NULL DEFAULT 'user',
    quota BIGINT NOT NULL DEFAULT 0,
    password_hash VARCHAR(512) NOT NULL
);

-- Insert seed users if they don't exist already
-- Passwords are managed by Vault at secret/app/flask

INSERT INTO users (username, role, quota, password_hash)
SELECT 'admin', 'admin', 0, '${ADMIN_HASH}'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin');

INSERT INTO users (username, role, quota, password_hash)
SELECT 'alice', 'user', 104857600, '${ALICE_HASH}'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'alice');

INSERT INTO users (username, role, quota, password_hash)
SELECT 'moderator', 'moderator', 0, '${MOD_HASH}'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'moderator');
EOF

echo "✅ SQL init script created at: $OUTPUT_FILE"
echo ""
echo "==================================="
echo "Next Steps"
echo "==================================="
echo ""
echo "1. Ensure the init script is enabled in docker-compose.yaml:"
echo "   Uncomment the volume mount in the 'db' service"
echo ""
echo "2. Reset the database to apply changes:"
echo "   docker compose down -v"
echo "   docker compose up -d"
echo ""
echo "   ⚠️  WARNING: This will delete all existing data!"
echo ""
echo "3. Or manually run the SQL script in the database:"
echo "   docker compose exec db psql -U admin -d postgres_db -f /docker-entrypoint-initdb.d/001_create_users.sql"
echo ""
