-- Create users table and seed initial users (admin, alice, moderator)
-- This script is executed by the official Postgres image when the DB directory is empty.
--
-- IMPORTANT: This file is auto-generated by vault/scripts/setup-vault-app.sh
-- Passwords are retrieved from Vault and hashed using werkzeug.security
--
-- To regenerate with updated passwords: Re-run setup-vault-app.sh

CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY,
    role VARCHAR(32) NOT NULL DEFAULT 'user',
    quota BIGINT NOT NULL DEFAULT 0,
    password_hash VARCHAR(512) NOT NULL
);

-- Insert seed users if they don't exist already
-- Passwords are managed by Vault at secret/mes_local_cloud/app/flask

INSERT INTO users (username, role, quota, password_hash)
SELECT 'admin', 'admin', 0, 'scrypt:32768:8:1$V4ydE600Vx2kVI2t$2b683518ac5a36cb323bfe091aab4d38c946cdbfe3f7b4c2e72eb3ddce408f30ca395613c438ca9400e86e36db12560b6992221582c7f9b297bbeb64cdacb7ad'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin');

INSERT INTO users (username, role, quota, password_hash)
SELECT 'alice', 'user', 104857600, 'scrypt:32768:8:1$BqiXqaiZbB4GKzcK$4949a26ea46b0ffaf11f88103cbe867b6a00aaa07050403e748c2362e90d7aeaf07e0e7b7c1cab8e4ede40d790146b42796c826ba8af906e9950e0fca818d5c8'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'alice');

INSERT INTO users (username, role, quota, password_hash)
SELECT 'moderator', 'moderator', 0, 'scrypt:32768:8:1$gSoM9myIzWuvij80$e337a3df09ce25586bf6e7f8b965ffb3004ed5b6f20cac3f152cdf0c95e95f685babb4c4a02aa01d2a0118a5f28efbf8714e5108f0e3b671cec6a8ae9935252a'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'moderator');
