-- Create users table and seed initial users (admin, alice, moderator)
-- This script is executed by the official Postgres image when the DB directory is empty.
--
-- IMPORTANT: This file is auto-generated by vault/scripts/setup-vault-app.sh
-- Passwords are retrieved from Vault and hashed using werkzeug.security
--
-- To regenerate with updated passwords: Re-run setup-vault-app.sh

CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY,
    role VARCHAR(32) NOT NULL DEFAULT 'user',
    quota BIGINT NOT NULL DEFAULT 0,
    password_hash VARCHAR(512) NOT NULL
);

-- Insert seed users if they don't exist already
-- Passwords are managed by Vault at secret/4_ldap_xacml/app/flask

INSERT INTO users (username, role, quota, password_hash)
SELECT 'admin', 'admin', 0, 'scrypt:32768:8:1$HsHTdd40QlxGkm8G$9080b4490ee5427c1efed372b05905282b46470bdb5a91840a544d434ec60b2e357c00d8d7c3b67468fdc3df5fe873850f7fbed6522f90448876dfe42f2f6e1e'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin');

INSERT INTO users (username, role, quota, password_hash)
SELECT 'alice', 'user', 104857600, 'scrypt:32768:8:1$s3tKR1ih3wDUE5tx$f6b8bf09ea46337ca542d1774d060b967378d4c2d5dc075992853fcfbdacd713b36e16cc713704d956c7459e8657a1901abf7842fe543121a14b704b509b646c'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'alice');

INSERT INTO users (username, role, quota, password_hash)
SELECT 'moderator', 'moderator', 0, 'scrypt:32768:8:1$Vjdq1RLdf90xSwDa$ccd4a6b54a0a5d9e44d52d0c8f32b5e8bf0ef8ccb6143b7ccba2378e3e3789c5e9337bf77f2831b9b09621bdaf46c8f63550decac0bde61b5a0184e58b231100'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'moderator');
