-- Create users table and seed initial users (admin, alice, moderator)
-- This script is executed by the official Postgres image when the DB directory is empty.
--
-- IMPORTANT: This file is auto-generated by vault/scripts/init-vault.sh
-- Passwords are retrieved from Vault and hashed using werkzeug.security
--
-- To regenerate with updated passwords: Re-run init-vault.sh or generate-db-init.sh

CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY,
    role VARCHAR(32) NOT NULL DEFAULT 'user',
    quota BIGINT NOT NULL DEFAULT 0,
    password_hash VARCHAR(512) NOT NULL
);

-- Insert seed users if they don't exist already
-- Passwords are managed by Vault at secret/app/flask

INSERT INTO users (username, role, quota, password_hash)
SELECT 'admin', 'admin', 0, 'scrypt:32768:8:1$qakQ3vUkmHmBdL3g$5589ade401280273a5b195d5900ad644e2047dfc980ac545a57157855e8937e9dc172a44e3b4666a1305b4b9ceea4ad8239abe0770d5f2fd168ce924eb494647'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin');

INSERT INTO users (username, role, quota, password_hash)
SELECT 'alice', 'user', 104857600, 'scrypt:32768:8:1$vBKktgI03ABPYaIf$da91ee692bfb9fa38ad19d797c7ecaccbd847efb45fd529295ab420a30e6e4960d94d51a220d9be23ea6784895474d5897d9c1c05e1bd236faecc8fe969189df'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'alice');

INSERT INTO users (username, role, quota, password_hash)
SELECT 'moderator', 'moderator', 0, 'scrypt:32768:8:1$ixKzNYbV7j0ZBHIl$ca91beb4c0413e68377bec479359077c3c6ed33578f32cf903441b492cad51ad9f639cbda9b9221673fb1ff4054e3e5590df63289fc98b3620b9d6e81a946a02'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'moderator');
